language: java
jdk: openjdk8
 

addons:
  sonarcloud:
    organization: "sanogotech"
    token:
      secure: "f7ea97b2308b7324dc8514c043d75924fd6920c6" # encrypted value of your token
 
before_script:
    #https://docs.travis-ci.com/user/environment-variables/
    # Always run script
    #- $TRAVIS_BUILD_DIR/ci/travis_release_audit.sh
    # CD Sub Projet
    #- cd  $TRAVIS_BUILD_DIR/subproject
    #

script:
#- mvn clean install -B
#- mvn clean  test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sanogotech_tpjunitwithspringbootrest 
#- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar